<?php
use App\Services\ProjectPayments; use App\Services\VibeNestAuth; use Illuminate\Http\Request; use Illuminate\Support\Facades\Route;
Route::get('/',fn()=>response('<h1>VibeNest Auth + Payments reference</h1><a href="/auth/vibenest/login">Sign in</a>'));
Route::get('/auth/vibenest/login',function(Request $request){$auth=VibeNestAuth::fromEnvironment();$flow=$auth->begin($auth->discovery());$request->session()->put('vibenest_oidc',$flow['pending']);return redirect()->away($flow['url'],303);});
Route::get('/auth/vibenest/callback',function(Request $request){$auth=VibeNestAuth::fromEnvironment();$user=$auth->complete($request->query(),$request->session()->pull('vibenest_oidc',[]),$auth->discovery());$request->session()->invalidate();$request->session()->regenerateToken();$request->session()->put('user',$user);return redirect()->away($auth->applicationOrigin().'/',303);});
Route::post('/auth/logout',function(Request $request){abort_unless($request->session()->has('user.subject'),401);$request->session()->invalidate();$request->session()->regenerateToken();return redirect('/',303);});
Route::get('/api/session',function(Request $request){abort_unless($request->session()->has('user.subject'),401);return response()->json(['authenticated'=>true]+$request->session()->get('user'));});
$payments=fn()=>new ProjectPayments((string)env('VIBENEST_PROJECT_PAYMENTS_WEBHOOK_SECRET'),(string)env('VIBENEST_PROJECT_PAYMENTS_ENVIRONMENT_ID'),(string)env('PROJECT_PAYMENT_FIXTURE_STORE','.data/project-payments.sqlite'));
$enabled=fn()=>abort_unless(env('VIBENEST_PROJECT_PAYMENTS_ENABLED')==='true'&&env('VIBENEST_PROJECT_PAYMENTS_PROVIDER')==='simulator',404);
$subject=function(Request $request):string{$value=$request->session()->get('user.subject');abort_unless(is_string($value)&&$value!=='',401);return $value;};
Route::get('/api/project-payments/prices',function()use($enabled){$enabled();return ['provider'=>'simulator','prices'=>ProjectPayments::CATALOG];});
Route::post('/api/project-payments/checkout',function(Request $request)use($enabled,$subject,$payments){$enabled();try{return $payments()->checkout($subject($request),$request->json()->all());}catch(RuntimeException $e){abort(400,$e->getMessage());}});
Route::post('/api/project-payments/portal',function(Request $request)use($enabled,$subject,$payments){$enabled();return $payments()->portal($subject($request));});
Route::post('/webhooks/project-payments',function(Request $request)use($enabled,$payments){$enabled();abort_if($request->header('Content-Encoding'),415);try{$payments()->acceptWebhook($request->getContent(),(string)$request->header('Paddle-Signature'));}catch(RuntimeException|JsonException $e){abort(400,$e->getMessage());}return response()->json(['accepted'=>true],202);});
Route::get('/.well-known/vibenest/project-payments/verifier',function(Request $request)use($enabled){$enabled();abort_unless(env('VIBENEST_PROJECT_PAYMENTS_VERIFIER_ENABLED')==='true'&&hash_equals((string)env('VIBENEST_PROJECT_PAYMENTS_WEBHOOK_SECRET'),(string)$request->header('X-VibeNest-Simulator-Secret')),404);return ['provider'=>'simulator','environmentId'=>env('VIBENEST_PROJECT_PAYMENTS_ENVIRONMENT_ID'),'manifestDigest'=>env('VIBENEST_PROJECT_PAYMENTS_MANIFEST_DIGEST'),'builtCommit'=>env('SOURCE_COMMIT')];});
