source "https://rubygems.org"
ruby ">= 3.3.0"
gem "rails", "8.1.3.1"
gem "puma", "8.0.2"
gem "sqlite3", "2.9.6"
gem "minitest", "6.0.6", group: :test
gem "bundler-audit", "0.9.3", group: :test
gem "tzinfo-data", "1.2026.3", platforms: %i[windows jruby]
